export const VERIFICATION_CONFIG = {
  AUTO_APPROVAL_THRESHOLD: 50,
  REPORT_EXPIRY_DAYS: 7,
  AUTO_EXPIRY_CHECK_INTERVAL_MINUTES: 60,
  MAX_SUBMISSION_IMAGES: 5,
  MIN_SUBMISSION_IMAGES: 1,
  N8N_WEBHOOK_URL: process.env.N8N_WEBHOOK_URL || "",
};

export default VERIFICATION_CONFIG;
