from ultralytics import YOLO
import os
import random

# 1. Load your trained model
# precise path to the weights generated by your training run
model = YOLO(r"E:\GreenTaxProject\runs\detect\green_tax_model\weights\compost_yolo_v1.pt")

# 2. Pick a random image from your Validation set to test
# We use validation because the model did NOT train on these images.
val_images_path = r"E:\GreenTaxProject\data\raw\val\images"
# Get all files first
all_files = os.listdir(val_images_path)

# Pick one randomly
test_image = random.choice(all_files)
source = os.path.join(val_images_path, test_image)

print(f"Testing on: {source}")

# 3. Run Prediction
results = model.predict(source, save=True, conf=0.5) 
# conf=0.5 means "Only show me boxes if you are 50% sure"

print(f"Prediction saved to: {results[0].save_dir}")
